//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.res.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CJ Fan Server requires you agree to their rules before you can chat freely. Please read the #rules channel for more information..
        /// </summary>
        internal static string AgreementNotice {
            get {
                return ResourceManager.GetString("AgreementNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a new member, you must agree to these rules, to do so, please enter the code below in #verify-channel.
        ///
        ///.
        /// </summary>
        internal static string AgreementPrompt {
            get {
                return ResourceManager.GetString("AgreementPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your confirmation was received, enjoy the server!.
        /// </summary>
        internal static string AgreementSuccess {
            get {
                return ResourceManager.GetString("AgreementSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command failed to execute. Please contact the server owner..
        /// </summary>
        internal static string CmdFailedToExecute {
            get {
                return ResourceManager.GetString("CmdFailedToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command ran out of time to respond..
        /// </summary>
        internal static string CmdOutOfTime {
            get {
                return ResourceManager.GetString("CmdOutOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is a list of commands that you currently have access to.
        ///
        ///To execute a command, chat the syntax provided for the desired command.
        ///
        ///- If a command spans multiple lines, you will need to provide multiple messages.
        ///- Text items on their own are required.
        ///- Optional items are surrounded by square brackets.
        ///- You need to choose an item for text items surrounded by braces, separated by vertical bars..
        /// </summary>
        internal static string HelpBody {
            get {
                return ResourceManager.GetString("HelpBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays help information for the bot..
        /// </summary>
        internal static string HelpDescription1 {
            get {
                return ResourceManager.GetString("HelpDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example:.
        /// </summary>
        internal static string HelpExample {
            get {
                return ResourceManager.GetString("HelpExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpName {
            get {
                return ResourceManager.GetString("HelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string HelpUsage {
            get {
                return ResourceManager.GetString("HelpUsage", resourceCulture);
            }
        }
    }
}
